######################################################################
# Automatically generated by qmake (2.01a) Fri Jun 12 17:25:30 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += board.h common.h comunication.h monitor.h TCPClient.h
SOURCES += board.cpp comunication.cpp main.cpp monitor.cpp TCPClient.cpp
