######################################################################
# Automatically generated by qmake (1.07a) Thu Jan 3 17:14:30 2008
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += board.h common.h comunication.h monitor.h TCPClient.h
SOURCES += board.cpp comunication.cpp main.cpp monitor.cpp TCPClient.cpp
